# CMake generated Testfile for 
# Source directory: /home/g/gh/firehose/globalprotect-cpp
# Build directory: /home/g/gh/firehose/globalprotect-cpp
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_options "/home/g/gh/firehose/globalprotect-cpp/test_options")
set_tests_properties(test_options PROPERTIES  _BACKTRACE_TRIPLES "/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;74;add_test;/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;0;")
add_test(test_random "/home/g/gh/firehose/globalprotect-cpp/test_random")
set_tests_properties(test_random PROPERTIES  _BACKTRACE_TRIPLES "/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;74;add_test;/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;0;")
add_test(test_html_escape "/home/g/gh/firehose/globalprotect-cpp/test_html_escape")
set_tests_properties(test_html_escape PROPERTIES  _BACKTRACE_TRIPLES "/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;74;add_test;/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;0;")
add_test(test_cert_policy "/home/g/gh/firehose/globalprotect-cpp/test_cert_policy")
set_tests_properties(test_cert_policy PROPERTIES  _BACKTRACE_TRIPLES "/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;74;add_test;/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;0;")
add_test(test_auth_server "/home/g/gh/firehose/globalprotect-cpp/test_auth_server")
set_tests_properties(test_auth_server PROPERTIES  _BACKTRACE_TRIPLES "/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;74;add_test;/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;0;")
add_test(test_callback_listener "/home/g/gh/firehose/globalprotect-cpp/test_callback_listener")
set_tests_properties(test_callback_listener PROPERTIES  _BACKTRACE_TRIPLES "/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;74;add_test;/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;0;")
add_test(test_secret_transport "/home/g/gh/firehose/globalprotect-cpp/test_secret_transport")
set_tests_properties(test_secret_transport PROPERTIES  _BACKTRACE_TRIPLES "/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;74;add_test;/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;0;")
add_test(test_service_key "/home/g/gh/firehose/globalprotect-cpp/test_service_key")
set_tests_properties(test_service_key PROPERTIES  _BACKTRACE_TRIPLES "/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;74;add_test;/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;0;")
add_test(test_http_client "/home/g/gh/firehose/globalprotect-cpp/test_http_client")
set_tests_properties(test_http_client PROPERTIES  _BACKTRACE_TRIPLES "/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;74;add_test;/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;0;")
add_test(test_cookie_store "/home/g/gh/firehose/globalprotect-cpp/test_cookie_store")
set_tests_properties(test_cookie_store PROPERTIES  _BACKTRACE_TRIPLES "/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;74;add_test;/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;0;")
add_test(test_xml "/home/g/gh/firehose/globalprotect-cpp/test_xml")
set_tests_properties(test_xml PROPERTIES  _BACKTRACE_TRIPLES "/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;74;add_test;/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;0;")
add_test(test_json "/home/g/gh/firehose/globalprotect-cpp/test_json")
set_tests_properties(test_json PROPERTIES  _BACKTRACE_TRIPLES "/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;74;add_test;/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;0;")
add_test(test_posture "/home/g/gh/firehose/globalprotect-cpp/test_posture")
set_tests_properties(test_posture PROPERTIES  _BACKTRACE_TRIPLES "/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;74;add_test;/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;0;")
add_test(test_gui "/home/g/gh/firehose/globalprotect-cpp/test_gui")
set_tests_properties(test_gui PROPERTIES  _BACKTRACE_TRIPLES "/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;74;add_test;/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;0;")
add_test(test_aead "/home/g/gh/firehose/globalprotect-cpp/test_aead")
set_tests_properties(test_aead PROPERTIES  _BACKTRACE_TRIPLES "/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;74;add_test;/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;0;")
add_test(test_ws "/home/g/gh/firehose/globalprotect-cpp/test_ws")
set_tests_properties(test_ws PROPERTIES  _BACKTRACE_TRIPLES "/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;74;add_test;/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;0;")
add_test(test_service_daemon "/home/g/gh/firehose/globalprotect-cpp/test_service_daemon")
set_tests_properties(test_service_daemon PROPERTIES  _BACKTRACE_TRIPLES "/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;74;add_test;/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;0;")
add_test(test_gateway_client "/home/g/gh/firehose/globalprotect-cpp/test_gateway_client")
set_tests_properties(test_gateway_client PROPERTIES  _BACKTRACE_TRIPLES "/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;74;add_test;/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;0;")
add_test(test_tunnel_client "/home/g/gh/firehose/globalprotect-cpp/test_tunnel_client")
set_tests_properties(test_tunnel_client PROPERTIES  _BACKTRACE_TRIPLES "/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;74;add_test;/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;0;")
add_test(test_client_flow "/home/g/gh/firehose/globalprotect-cpp/test_client_flow")
set_tests_properties(test_client_flow PROPERTIES  _BACKTRACE_TRIPLES "/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;74;add_test;/home/g/gh/firehose/globalprotect-cpp/CMakeLists.txt;0;")
